---
- name: Device Health Validation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Check WinRM
      wait_for:
        host: "{{ target_ip }}"
        port: "{{ winrm_port | default(5985)}}"
        timeout: 20
