---
- name: Device Health Validation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Check WinRM
      wait_for:
        host: "{{ target_ip }}"
        port: 5986
        timeout: 20
      register: connectivity
      ignore_errors: true

    - name: Launch AWS Recovery
      command: >
        ansible-playbook playbook/aws_windows_recovery.yml
        -e target_host={{ target_host }}
        -e target_ip={{ target_ip }}
      when: connectivity.failed
